#!/bin/bash
# aliyun-batch-add-accts.sh — 批量给阿里云 carher chatgpt 池加 N 个新账号
#
# 前提：5 个新账号 OAuth 已完成（auth.json 在 188:/Data/chatgpt-auth/acct-N/auth.json）
# 输入：account 编号 list（空格分隔，如 "17 18 19 20 21"）
#
# 这个脚本只做"阿里云迁入"那一段（onboarding 流程的 phase B-E）：
#   B. 生成 manifest (PVC + Deployment + Service for each acct)
#   C. kubectl apply
#   D. kubectl cp auth.json from 188 → aliyun PVC + rollout restart
#   E. patch canary ConfigMap (add 20 model entries) + apply + rollout restart canary
#   F. smoke test (port-forward, 20 calls 看 LB 命中)
#   G. 188 停容器 (避免 token_invalidated)
#
# 不做：188 OAuth（由 add-chatgpt-account.sh acct-N --oauth 单独完成，每 acct ~8min 串行）
# 不做：198 prod 注册/清理（这批账号专属阿里云，不入 198）
#
# 用法：
#   ./scripts/aliyun-batch-add-accts.sh 17 18 19 20 21
#   ./scripts/aliyun-batch-add-accts.sh --skip-stop-188 17 18 19    # 跳过 188 容器停
#   ./scripts/aliyun-batch-add-accts.sh --dry-run 17                # 只生成 manifest + ConfigMap patch 不 apply

set -euo pipefail

DRY_RUN=0
SKIP_STOP_188=0
while [[ "${1:-}" == --* ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --skip-stop-188) SKIP_STOP_188=1; shift ;;
    *) echo "unknown flag: $1"; exit 1 ;;
  esac
done

if [[ $# -lt 1 ]]; then
  echo "用法: $0 [--dry-run] [--skip-stop-188] N1 N2 N3 ..."
  echo "  示例: $0 17 18 19 20 21"
  exit 1
fi

ACCTS=("$@")
SSH_188="cltx@10.68.13.188"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "================================"
echo "阿里云 chatgpt-acct 批量上线"
echo "账号: ${ACCTS[*]}"
echo "DRY_RUN: $DRY_RUN  SKIP_STOP_188: $SKIP_STOP_188"
echo "================================"

# ── Pre-check ───────────────────────────────────────────────────────────────
echo "==[pre-check]== 验证依赖"
# kubectl tunnel
if ! kubectl get ns carher >/dev/null 2>&1; then
  echo "❌ kubectl 没连通 aliyun K8s"
  echo "   启 tunnel: nohup scripts/jms proxy laoyang 16443 172.16.1.163 6443 > /tmp/jms-proxy.log 2>&1 &"
  exit 1
fi
# 188 上 auth.json 全部存在
for N in "${ACCTS[@]}"; do
  if ! ssh "$SSH_188" "test -s /Data/chatgpt-auth/acct-$N/auth.json"; then
    echo "❌ 188:/Data/chatgpt-auth/acct-$N/auth.json 不存在或为空 — 先跑 add-chatgpt-account.sh acct-$N --oauth"
    exit 1
  fi
done
echo "  ✅ 5 个 auth.json 全部就位"

# ── B. 生成 manifest ────────────────────────────────────────────────────────
MANIFEST=/tmp/aliyun-chatgpt-acct-pool-batch.yaml
python3 - "${ACCTS[@]}" > "$MANIFEST" << 'PY'
import sys
accts = [int(x) for x in sys.argv[1:]]

def block(n):
    return f"""---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {{name: chatgpt-acct-{n}-auth, namespace: carher, labels: {{pool: chatgpt-acct, account: "{n}"}}}}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: alibabacloud-cnfs-nas
  resources: {{requests: {{storage: 1Gi}}}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-acct-{n}
  namespace: carher
  labels: {{app: chatgpt-acct-{n}, pool: chatgpt-acct, account: "{n}"}}
spec:
  replicas: 1
  strategy: {{type: Recreate}}
  selector:
    matchLabels: {{app: chatgpt-acct-{n}}}
  template:
    metadata:
      labels: {{app: chatgpt-acct-{n}, pool: chatgpt-acct, account: "{n}"}}
    spec:
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:v1.85.0
          imagePullPolicy: IfNotPresent
          args: ["--config", "/app/config.yaml", "--port", "4000"]
          ports: [{{containerPort: 4000}}]
          env:
            - {{name: CHATGPT_TOKEN_DIR, value: /chatgpt-auth}}
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef: {{name: chatgpt-pool-master-key, key: LITELLM_MASTER_KEY}}
          resources:
            requests: {{cpu: 100m, memory: 256Mi}}
            limits: {{cpu: "1", memory: 2Gi}}
          readinessProbe:
            httpGet: {{path: /health/readiness, port: 4000}}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            httpGet: {{path: /health/liveliness, port: 4000}}
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - {{name: config, mountPath: /app/config.yaml, subPath: config.yaml, readOnly: true}}
            - {{name: auth, mountPath: /chatgpt-auth}}
      volumes:
        - {{name: config, configMap: {{name: chatgpt-pool-config}}}}
        - {{name: auth, persistentVolumeClaim: {{claimName: chatgpt-acct-{n}-auth}}}}
---
apiVersion: v1
kind: Service
metadata:
  name: chatgpt-acct-{n}
  namespace: carher
  labels: {{app: chatgpt-acct-{n}, pool: chatgpt-acct, account: "{n}"}}
spec:
  type: ClusterIP
  selector: {{app: chatgpt-acct-{n}}}
  ports: [{{port: 4000, targetPort: 4000}}]
"""

print(f"# Auto-generated by aliyun-batch-add-accts.sh for acct-{','.join(str(a) for a in accts)}")
for n in accts:
    print(block(n))
PY
echo "==[B]== generated $MANIFEST ($(grep -c '^---' "$MANIFEST") resources)"

# ── C. apply manifest ──────────────────────────────────────────────────────
if [[ $DRY_RUN -eq 1 ]]; then
  echo "==[C]== dry-run: kubectl apply -f $MANIFEST --dry-run=server"
  kubectl apply -f "$MANIFEST" --dry-run=server 2>&1 | tail -20
else
  echo "==[C]== kubectl apply"
  kubectl apply -f "$MANIFEST" 2>&1 | tail -20
fi

# ── D. kubectl cp auth.json + rollout restart ──────────────────────────────
if [[ $DRY_RUN -eq 0 ]]; then
  echo "==[D]== cp auth.json from 188 → aliyun PVC + rollout restart"
  mkdir -p /tmp/aliyun-auth
  for N in "${ACCTS[@]}"; do
    # wait pod created (max 30s)
    for i in $(seq 1 15); do
      POD=$(kubectl get pod -n carher -l app=chatgpt-acct-$N -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
      [[ -n "$POD" ]] && break
      sleep 2
    done
    if [[ -z "${POD:-}" ]]; then
      echo "  ⚠ acct-$N pod not created in 30s, skip"; continue
    fi
    scp -q "$SSH_188:/Data/chatgpt-auth/acct-$N/auth.json" /tmp/aliyun-auth/auth-$N.json
    kubectl cp /tmp/aliyun-auth/auth-$N.json carher/$POD:/chatgpt-auth/auth.json -c litellm 2>&1 | tail -1
    echo "  ✓ acct-$N auth.json → $POD"
  done
  echo "  rollout restart..."
  for N in "${ACCTS[@]}"; do
    kubectl rollout restart deployment/chatgpt-acct-$N -n carher 2>&1 | tail -1
  done
  echo "  等 Pod ready (sleep 45s)..."
  sleep 45
  kubectl get pod -n carher -l pool=chatgpt-acct 2>&1 | head -15
fi

# ── E. prod + canary ConfigMap patch (两个都要,carher her 默认走 prod) ────
# 复用同一 patch 算法,patch 2 个 yaml file
PATCH_CONFIGS=(
  "$REPO_ROOT/k8s/litellm-proxy.yaml"               # prod (monolithic, includes ConfigMap litellm-config)
  "$REPO_ROOT/k8s/litellm-proxy-canary-config.yaml" # canary independent ConfigMap
)
ACCTS_CSV="$(IFS=,; echo "${ACCTS[*]}")"

for cfg in "${PATCH_CONFIGS[@]}"; do
  PATCHED="/tmp/$(basename "$cfg").patched"
  echo "  patching $(basename "$cfg")..."
  CFG_SRC="$cfg" CFG_OUT="$PATCHED" ACCTS_CSV="$ACCTS_CSV" python3 <<'PY'
import os, re, sys
src = os.environ["CFG_SRC"]
out = os.environ["CFG_OUT"]
accts = [int(x) for x in os.environ["ACCTS_CSV"].split(",")]
ID_MAP = {
    "chatgpt-gpt-5.5": "chatgpt-gpt-5.5",
    "gpt-5.4": "gpt-5.4",
    "gpt-5.3-codex": "gpt-5.3-codex",
    "gpt-5.3-codex-spark": "gpt-5.3-codex-spark",
}
content = open(src).read()

def entry(model_name, id_suffix, n):
    return (f"      - model_name: {model_name}\n"
            f"        litellm_params:\n"
            f"          model: openai/{model_name}\n"
            f"          api_base: http://chatgpt-acct-{n}.carher.svc:4000\n"
            f"          api_key: os.environ/CHATGPT_POOL_KEY\n"
            f"        model_info: {{mode: responses, id: chatgpt-acct-{n}/{id_suffix}}}\n")

for model_name, id_suffix in ID_MAP.items():
    pat = re.compile(r"(        model_info: \{mode: responses, id: chatgpt-acct-(\d+)/" + re.escape(id_suffix) + r"\})\n")
    matches = list(pat.finditer(content))
    if not matches:
        print(f"  ⚠ no marker for {model_name} in {os.path.basename(src)}", file=sys.stderr); continue
    last = matches[-1]
    new_accts = [n for n in accts if not re.search(rf"chatgpt-acct-{n}/" + re.escape(id_suffix) + r"\}", content)]
    if not new_accts: continue
    new_block = "".join(entry(model_name, id_suffix, n) for n in new_accts)
    content = content[:last.end()] + new_block + content[last.end():]
    print(f"    ✓ {model_name}: +{len(new_accts)} entries")

open(out, "w").write(content)
PY

  if [[ $DRY_RUN -eq 1 ]]; then
    echo "    DRY: would write back to $cfg, kubectl apply, rollout restart"
  else
    cp "$PATCHED" "$cfg"
    kubectl apply -f "$cfg" 2>&1 | tail -3
  fi
done

if [[ $DRY_RUN -eq 0 ]]; then
  echo "  rollout restart prod + canary..."
  kubectl rollout restart deployment/litellm-proxy -n carher
  kubectl rollout restart deployment/litellm-proxy-canary -n carher
  echo "  等 rollout (sleep 90s, hostPort surge=1 慢)..."
  sleep 90
  kubectl get pod -n carher -l app=litellm-proxy 2>&1 | head -5
  kubectl get pod -n carher -l app=litellm-proxy-canary 2>&1 | head -3
fi

if [[ $DRY_RUN -eq 1 ]]; then
  echo "==[E]== dry-run: would patch + apply prod + canary"
  for N in "${ACCTS[@]}"; do
    echo "    acct-$N mentions in prod yaml: $(grep -c "chatgpt-acct-$N.carher.svc" /tmp/litellm-proxy.yaml.patched 2>/dev/null || echo 0)"
    echo "    acct-$N mentions in canary yaml: $(grep -c "chatgpt-acct-$N.carher.svc" /tmp/litellm-proxy-canary-config.yaml.patched 2>/dev/null || echo 0)"
  done
else
  echo "==[E]== prod + canary patched + applied + rollout"
fi

# ── F. smoke test ───────────────────────────────────────────────────────────
if [[ $DRY_RUN -eq 0 ]]; then
  echo "==[F]== smoke test 20 calls via canary"
  kubectl port-forward -n carher svc/litellm-proxy-canary 14444:4000 > /tmp/pf-canary-batch.log 2>&1 &
  PFPID=$!
  sleep 3
  CANARY_POD=$(kubectl get pod -n carher -l app=litellm-proxy-canary -o jsonpath='{.items[?(@.status.containerStatuses[0].ready==true)].metadata.name}' | head -1)
  LMK=$(kubectl exec -n carher $CANARY_POD -c litellm -- printenv LITELLM_MASTER_KEY)
  HITS=""
  for i in $(seq 1 20); do
    H=$(curl -sSD - -o /dev/null -X POST http://localhost:14444/v1/chat/completions \
      -H "Authorization: Bearer $LMK" -H "Content-Type: application/json" \
      -d '{"model":"chatgpt-gpt-5.5","messages":[{"role":"user","content":"hi"}],"max_tokens":1,"stream":true}' \
      --max-time 30 2>&1 | grep -i "x-litellm-model-id:" | grep -oE "acct-[0-9]+" | head -1)
    HITS="$HITS $H"
  done
  echo "  20-call LB distribution:"
  echo "$HITS" | tr ' ' '\n' | sort | uniq -c | sed 's/^/    /'
  kill $PFPID 2>/dev/null || true
fi

# ── G. 停 188 容器 (避免 token_invalidated) ────────────────────────────────
if [[ $DRY_RUN -eq 0 && $SKIP_STOP_188 -eq 0 ]]; then
  echo "==[G]== 停 188 acct 容器 (避免同账号两处用)"
  for N in "${ACCTS[@]}"; do
    ssh "$SSH_188" "cd /Data/chatgpt-auth && docker compose stop litellm-chatgpt-$N 2>&1 | tail -1"
  done
  echo "  ✓ 188 容器已停; 阿里云独占运行"
fi

echo
echo "🎉 完成! 5 个 acct 上线阿里云 carher pool"
echo "下一步:"
echo "  - 监控: scripts/chatgpt-acct-spend.sh aliyun 2h"
echo "  - 容器健康: kubectl get pod -n carher -l pool=chatgpt-acct"
echo "  - canary: kubectl get pod -n carher -l app=litellm-proxy-canary"
echo "  - git commit k8s/chatgpt-acct-pool.yaml (手动 merge $MANIFEST) + k8s/litellm-proxy-canary-config.yaml"
