#!/usr/bin/env python3
"""Sync compact CarHer fusion base metrics into the Feishu Base evidence table.

This script reads the JSONL generated by carher_fusion_diagnosis_batch.py and
upserts one row per Her. It does not read K8s/PVC/raw chat data and does not
score; its job is to make the model-ready evidence auditable in Feishu.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import time
from pathlib import Path
from typing import Any


DEFAULT_BASE_TOKEN = "MOf3bvGYxa9rVSsbejscvTHon1g"
DEFAULT_TABLE_ID = "tbln4E5SyJNoOi2g"

FIELD_ORDER = [
    "Her ID",
    "检查周期开始",
    "检查周期结束",
    "采集状态",
    "群消息数",
    "Bot Mention 数",
    "群活跃天数",
    "覆盖群数",
    "近期文件数",
    "文件活跃天数",
    "Workspace 文件数",
    "Feishu Groups 文件数",
    "Memory 文件区数",
    "Logs 文件数",
    "Memory DB 状态",
    "Memory files",
    "Memory chunks",
    "Memory FTS chunks",
    "Embedding cache",
    "Top 主题",
    "数据质量告警",
    "低置信字段",
    "Evidence JSON",
    "Pod 名称",
    "Bot Alias 已配置",
    "Owner Alias 已配置",
    "报告链接",
]


def run_json(cmd: list[str], cwd: Path | None = None) -> dict[str, Any]:
    proc = subprocess.run(cmd, text=True, capture_output=True, cwd=str(cwd) if cwd else None)
    if proc.returncode:
        raise RuntimeError(proc.stderr or proc.stdout)
    data = json.loads(proc.stdout)
    if not data.get("ok"):
        raise RuntimeError(json.dumps(data, ensure_ascii=False))
    return data


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def load_report_links(path: Path | None) -> dict[str, str]:
    if not path:
        return {}
    links: dict[str, str] = {}
    for item in load_jsonl(path):
        her_id = str(item.get("her_id") or "")
        if not her_id:
            continue
        url = item.get("wiki_url") or item.get("url") or item.get("report_link")
        if isinstance(url, str) and url:
            links[her_id] = url
    return links


def list_existing(base_token: str, table_id: str) -> dict[str, str]:
    existing: dict[str, str] = {}
    offset = 0
    while True:
        data = run_json([
            "lark-cli",
            "base",
            "+record-list",
            "--base-token",
            base_token,
            "--table-id",
            table_id,
            "--offset",
            str(offset),
            "--limit",
            "200",
            "--format",
            "json",
            "--field-id",
            "Her ID",
        ])
        payload = data["data"]
        fields = payload["fields"]
        idx = {field: i for i, field in enumerate(fields)}
        her_idx = idx.get("Her ID")
        for record_id, row in zip(payload["record_id_list"], payload["data"]):
            her_id = row[her_idx] if her_idx is not None and her_idx < len(row) else None
            if her_id:
                existing[str(her_id)] = record_id
        if not payload.get("has_more"):
            break
        offset += 200
    return existing


def scalar(value: Any) -> Any:
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def period_value(record: dict[str, Any], key: str) -> str | None:
    period = record.get("period") or (record.get("base_metrics") or {}).get("period") or {}
    value = period.get(key)
    return str(value) if value else None


def evidence_json(record: dict[str, Any]) -> str:
    body = {
        "base_metrics": record.get("base_metrics") or {},
        "relative_metrics": record.get("relative_metrics") or {},
        "data_quality_warnings": record.get("data_quality_warnings") or [],
    }
    return json.dumps(body, ensure_ascii=False, sort_keys=True)[:18000]


def record_fields(record: dict[str, Any], report_links: dict[str, str] | None = None) -> dict[str, Any]:
    metrics = record.get("base_metrics") or {}
    warnings = record.get("data_quality_warnings") or metrics.get("data_quality_warnings") or []
    low_confidence = record.get("low_confidence_fields") or metrics.get("low_confidence_fields") or []
    her_id = str(record.get("her_id") or metrics.get("her_id") or f"carher-{record.get('uid')}")
    report_link = (report_links or {}).get(her_id)
    return {
        "Her ID": her_id,
        "检查周期开始": period_value(record, "start"),
        "检查周期结束": period_value(record, "end"),
        "采集状态": [str(record.get("status") or "unknown")],
        "群消息数": scalar(metrics.get("group_recent_messages") or 0),
        "Bot Mention 数": scalar(metrics.get("group_bot_mentions") or 0),
        "群活跃天数": scalar(metrics.get("group_active_days") or 0),
        "覆盖群数": scalar(metrics.get("groups_with_recent_messages") or 0),
        "近期文件数": scalar(metrics.get("files_recent_count") or 0),
        "文件活跃天数": scalar(metrics.get("files_recent_active_days") or 0),
        "Workspace 文件数": scalar(metrics.get("workspace_recent_files") or 0),
        "Feishu Groups 文件数": scalar(metrics.get("feishu_groups_recent_files") or 0),
        "Memory 文件区数": scalar(metrics.get("memory_recent_files") or 0),
        "Logs 文件数": scalar(metrics.get("logs_recent_files") or 0),
        "Memory DB 状态": str(metrics.get("memory_status") or ""),
        "Memory files": scalar(metrics.get("memory_files") or 0),
        "Memory chunks": scalar(metrics.get("memory_chunks") or 0),
        "Memory FTS chunks": scalar(metrics.get("memory_fts_chunks") or 0),
        "Embedding cache": scalar(metrics.get("embedding_cache") or 0),
        "Top 主题": str(metrics.get("topic_summary") or "")[:1800],
        "数据质量告警": ", ".join(str(item) for item in warnings)[:1800],
        "低置信字段": ", ".join(str(item) for item in low_confidence)[:1000],
        "Evidence JSON": evidence_json(record),
        "Pod 名称": str(metrics.get("pod") or record.get("pod") or ""),
        "Bot Alias 已配置": bool(metrics.get("bot_aliases_configured")),
        "Owner Alias 已配置": bool(metrics.get("owner_aliases_configured")),
        "报告链接": report_link,
    }


def chunked(items: list[Any], size: int) -> list[list[Any]]:
    return [items[index:index + size] for index in range(0, len(items), size)]


def sync(args: argparse.Namespace) -> dict[str, Any]:
    records = load_jsonl(Path(args.evidence))
    report_links = load_report_links(Path(args.report_links) if args.report_links else None)
    existing = list_existing(args.base_token, args.table_id)
    updates = []
    creates = []

    for record in records:
        her_id = str(record.get("her_id") or f"carher-{record.get('uid')}")
        fields = record_fields(record, report_links)
        if her_id in existing:
            updates.append({"record_id": existing[her_id], "fields": fields})
        else:
            creates.append(fields)

    out_dir = Path(args.audit_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "planned-updates.json").write_text(json.dumps(updates, ensure_ascii=False, indent=2))
    (out_dir / "planned-creates.json").write_text(json.dumps(creates, ensure_ascii=False, indent=2))
    if args.dry_run:
        return {"updates": len(updates), "creates": len(creates), "dry_run": True}

    updated = 0
    for item in updates:
        run_json([
            "lark-cli",
            "base",
            "+record-upsert",
            "--base-token",
            args.base_token,
            "--table-id",
            args.table_id,
            "--record-id",
            item["record_id"],
            "--json",
            json.dumps(item["fields"], ensure_ascii=False),
            "--format",
            "json",
        ])
        updated += 1

    created = 0
    batches = chunked(creates, args.batch_size)
    for batch_index, rows in enumerate(batches, start=1):
        body = {"fields": FIELD_ORDER, "rows": [[row.get(field) for field in FIELD_ORDER] for row in rows]}
        body_path = out_dir / f"create-batch-{batch_index}.json"
        body_path.write_text(json.dumps(body, ensure_ascii=False))
        data = run_json([
            "lark-cli",
            "base",
            "+record-batch-create",
            "--base-token",
            args.base_token,
            "--table-id",
            args.table_id,
            "--json",
            f"@{body_path.name}",
            "--format",
            "json",
        ], cwd=out_dir)
        created += len(data.get("data", {}).get("record_id_list") or [])
        if args.sleep_seconds and batch_index < len(batches):
            time.sleep(args.sleep_seconds)

    return {"updates": len(updates), "updated": updated, "creates": len(creates), "created": created, "dry_run": False}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence", required=True, help="Evidence JSONL from carher_fusion_diagnosis_batch.py.")
    parser.add_argument("--base-token", default=DEFAULT_BASE_TOKEN)
    parser.add_argument("--table-id", default=DEFAULT_TABLE_ID)
    parser.add_argument("--audit-dir", default="/tmp/carher-fusion-runs/base-metrics-table-sync")
    parser.add_argument("--report-links", help="Optional JSONL manifest/wiki-move audit with her_id -> wiki_url/url/report_link.")
    parser.add_argument("--batch-size", type=int, default=50)
    parser.add_argument("--sleep-seconds", type=float, default=1.5)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> int:
    result = sync(parse_args())
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
