#!/usr/bin/env python3
"""Render and publish CarHer fusion diagnosis reports from scored evidence.

The report stage is intentionally downstream-only: it consumes the compact
evidence JSONL and score JSONL generated by the batch/scoring scripts, then
creates sanitized Lark docs and writes the doc URLs back to the score table.
It must not read raw PVC/chat/session data.
"""

from __future__ import annotations

import argparse
import html
import json
import subprocess
import sys
import time
from pathlib import Path
from typing import Any


DEFAULT_BASE_TOKEN = "GBRPbLmFZaut74s8iFkcis8xnae"
DEFAULT_TABLE_ID = "tblHoikuAaekwki5"

SUBSCORES = [
    ("A1", "交互频次", 10),
    ("A2", "场景覆盖", 8),
    ("A3", "时间分布", 4),
    ("A4", "信息录入", 4),
    ("A5", "群聊覆盖", 4),
    ("B1", "课题深度", 12),
    ("B2", "数据支撑度", 8),
    ("B3", "认知增量归因", 10),
    ("B4", "元认知讨论", 10),
    ("C1", "不可替代产出", 8),
    ("C2", "组织传导率", 8),
    ("C3", "认知时间释放", 4),
    ("D1", "月度能力扩展", 5),
    ("D2", "失败修复率", 5),
]

TOTALS = [
    ("A", "连接强度", "A_total", 30),
    ("B", "融合质量", "B_total", 40),
    ("C", "融合效果", "C_total", 20),
    ("D", "进化能力", "D_total", 10),
]

METRIC_LABELS = {
    "group_recent_messages": "群消息",
    "group_bot_mentions": "Bot mention",
    "group_active_days": "群活跃天数",
    "groups_with_recent_messages": "覆盖群数",
    "files_recent_count": "近期文件",
    "workspace_recent_files": "workspace 文件",
    "memory_chunks": "Memory chunks",
    "memory_files": "Memory 文件",
    "feishu_groups_recent_files": "群归档文件",
    "files_recent_active_days": "文件活跃天数",
}


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def is_retryable_error(output: str) -> bool:
    try:
        data = json.loads(output)
    except json.JSONDecodeError:
        return False
    error = data.get("error") or {}
    return bool(error.get("retryable")) or error.get("subtype") == "rate_limit"


def run_json(cmd: list[str], cwd: Path | None = None, retries: int = 6) -> dict[str, Any]:
    delay = 5.0
    last_output = ""
    for attempt in range(retries + 1):
        proc = subprocess.run(cmd, text=True, capture_output=True, cwd=str(cwd) if cwd else None)
        last_output = proc.stderr or proc.stdout
        if proc.returncode == 0:
            data = json.loads(proc.stdout)
            if data.get("ok"):
                return data
            last_output = json.dumps(data, ensure_ascii=False)
        if attempt < retries and is_retryable_error(last_output):
            time.sleep(delay)
            delay = min(delay * 1.8, 60.0)
            continue
        raise RuntimeError(last_output)
    raise RuntimeError(last_output)


def selected_uids(args: argparse.Namespace) -> set[int] | None:
    values: set[int] = set()
    for item in args.uids or []:
        if "-" in item:
            start, end = item.split("-", 1)
            values.update(range(int(start), int(end) + 1))
        else:
            values.add(int(item))
    return values or None


def by_her_id(rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {str(row.get("her_id")): row for row in rows if row.get("her_id")}


def e(text: Any) -> str:
    return html.escape(str(text), quote=True)


def pct(relative: dict[str, Any], name: str) -> str:
    item = relative.get(name) or {}
    rank = item.get("percentile_rank")
    tier = item.get("tier") or "no_signal"
    if rank is None:
        return tier
    return f"{tier} / P{round(float(rank) * 100)}"


def cell(value: Any) -> str:
    return f"<td>{e(value)}</td>"


def score_comment(code: str, value: int, max_value: int, base: dict[str, Any], relative: dict[str, Any]) -> str:
    if code.startswith("A"):
        return {
            "A1": f"群消息 {base.get('group_recent_messages', 0)}，Bot mention {base.get('group_bot_mentions', 0)}，相对档位 {pct(relative, 'group_recent_messages')}",
            "A2": f"覆盖群 {base.get('groups_with_recent_messages', 0)}，近期文件 {base.get('files_recent_count', 0)}，Memory chunks {base.get('memory_chunks', 0)}",
            "A3": f"群活跃 {base.get('group_active_days', 0)} 天，文件活跃 {base.get('files_recent_active_days', 0)} 天",
            "A4": f"Memory chunks {base.get('memory_chunks', 0)}，档位 {pct(relative, 'memory_chunks')}",
            "A5": f"覆盖群 {base.get('groups_with_recent_messages', 0)}，档位 {pct(relative, 'groups_with_recent_messages')}",
        }.get(code, "")
    if code.startswith("B"):
        return {
            "B1": f"Top 主题：{base.get('topic_summary') or '无显著主题'}",
            "B2": "由群归档、workspace 文件、memory DB 三类聚合证据共同支撑",
            "B3": "系统只能识别纠偏/模板/源头逻辑等证据线索，具体归因待 owner/Her 复核",
            "B4": "按自诊断、纠偏、模板、质量体系等元认知关键词证据估算",
        }.get(code, "")
    if code.startswith("C"):
        return {
            "C1": "系统只能用文件/产出密度估算，不等于已经确认不可替代；需Her/owner确认产出价值",
            "C2": "系统只能用群消息/覆盖群估算传播，不等于组织传导成功；正式采纳需Her/owner确认",
            "C3": "系统只能用沉淀规模估算时间释放，不等于确认释放时间已投入高价值工作",
        }.get(code, "")
    return {
        "D1": "以质量体系/自诊断/模板等能力扩展线索估算",
        "D2": "以纠偏/源头逻辑/模板修复线索估算，复发率待 owner 复核",
    }.get(code, f"{value}/{max_value}")


def render_report(score: dict[str, Any], evidence: dict[str, Any], score_summary: dict[str, Any]) -> str:
    her_id = str(score["her_id"])
    uid = score.get("uid")
    period = score.get("period") or {}
    scores = score["scores"]
    base = evidence.get("base_metrics") or score.get("evidence_refs", {}).get("base_metrics") or {}
    relative = evidence.get("relative_metrics") or score.get("evidence_refs", {}).get("relative_metrics") or {}
    warnings = base.get("data_quality_warnings") or []
    top_topics = base.get("topic_strength_top") or []
    privacy = base.get("privacy") or {}

    title = f"{her_id} 融合体自诊断报告（2026-05-01～2026-06-12）"
    low_fields = ", ".join(score.get("low_confidence_fields") or [])
    warning_text = "；".join(warnings) if warnings else "无数据质量告警"

    summary_rows = "".join(
        "<tr>"
        + cell(f"{prefix} {name}")
        + cell(max_value)
        + cell(scores[key])
        + cell("系统证据分（C类需Her/owner复核）" if prefix == "C" else "系统证据分")
        + "</tr>"
        for prefix, name, key, max_value in TOTALS
    )
    sub_rows = "".join(
        "<tr>"
        + cell(f"{code} {name}")
        + cell(max_value)
        + cell(scores[code])
        + cell(score_comment(code, int(scores[code]), max_value, base, relative))
        + "</tr>"
        for code, name, max_value in SUBSCORES
    )
    metric_rows = "".join(
        "<tr>"
        + cell(label)
        + cell(base.get(name, 0))
        + cell(pct(relative, name))
        + "</tr>"
        for name, label in METRIC_LABELS.items()
    )
    topic_rows = "".join(
        "<tr>"
        + cell(item.get("keyword"))
        + cell(item.get("weighted_evidence", 0))
        + cell(item.get("group_occurrences", 0))
        + cell(item.get("recent_file_occurrences", 0))
        + cell(item.get("memory_hits", 0))
        + "</tr>"
        for item in top_topics[:8]
    )
    failure_rows = [
        ("认知松弛", "仅能从活跃度和主题连续性间接判断；本报告不自动给出主观定性。"),
        ("迎合陷阱", "系统按全员分位归一化评分，避免单个 Her 自述导致普遍高分。"),
        ("信息茧房", "以 Top 主题集中度观察风险；具体业务覆盖完整性需 owner 复核。"),
        ("能力幻觉", "报告不输出原文、不读取完整 payload，低置信字段已显式标注。"),
        ("过度依赖", "owner 侧消息识别因缺少 owner alias 暂不可用，暂不自动判断依赖程度。"),
        ("信息安全", "仅使用聚合计数、主题占位和相对分位；不包含原始私聊、密钥、token、open id。"),
    ]
    failure_table = "".join("<tr>" + cell(a) + cell(b) + "</tr>" for a, b in failure_rows)

    return f"""<title>{e(title)}</title>
<callout emoji="ℹ️" background-color="light-blue" border-color="blue">
  <p><b>结论：</b>{e(her_id)} 本周期系统证据分为 <b>{scores['total']}/100</b>，等级 <b>{e(score['grade'])}</b>，置信度 <b>{e(score['confidence'])}</b>。</p>
  <p>本报告由脚本化基础数据生成，周期为 {e(period.get('start'))} 至 {e(period.get('end'))}；主观项不作为最终确认分。</p>
</callout>

<h1>汇总</h1>
<table>
  <thead><tr><th background-color="light-gray">维度</th><th background-color="light-gray">满分</th><th background-color="light-gray">得分</th><th background-color="light-gray">口径</th></tr></thead>
  <tbody>{summary_rows}<tr>{cell('总分')}{cell(100)}{cell(scores['total'])}{cell(score['grade'])}</tr></tbody>
</table>

<callout emoji="❗" background-color="light-yellow" border-color="yellow">
  <p><b>待复核字段：</b>{e(low_fields or '无')}。这些字段有系统证据，但仍需要 owner/Her 结合真实业务闭环确认。</p>
  <p><b>数据质量：</b>{e(warning_text)}</p>
</callout>

<callout emoji="❗" background-color="light-yellow" border-color="yellow">
  <p><b>C类校准口径：</b>C1/C2/C3 是系统证据分，只能说明“有产出/有传播/有沉淀”的证据强弱；不可替代产出、组织传导是否成功、认知时间是否真正释放，必须由 Her/owner 自检确认后才进入最终确认分。</p>
</callout>

<hr/>
<h1>A. 连接强度（30分）</h1>
<table>
  <thead><tr><th background-color="light-gray">字段</th><th background-color="light-gray">满分</th><th background-color="light-gray">得分</th><th background-color="light-gray">证据摘要</th></tr></thead>
  <tbody>{''.join('<tr>' + cell(f'{c} {n}') + cell(m) + cell(scores[c]) + cell(score_comment(c, int(scores[c]), m, base, relative)) + '</tr>' for c, n, m in SUBSCORES[:5])}</tbody>
</table>

<h1>B. 融合质量（40分）</h1>
<table>
  <thead><tr><th background-color="light-gray">字段</th><th background-color="light-gray">满分</th><th background-color="light-gray">得分</th><th background-color="light-gray">证据摘要</th></tr></thead>
  <tbody>{''.join('<tr>' + cell(f'{c} {n}') + cell(m) + cell(scores[c]) + cell(score_comment(c, int(scores[c]), m, base, relative)) + '</tr>' for c, n, m in SUBSCORES[5:9])}</tbody>
</table>

<h1>C. 融合效果（20分，系统证据分）</h1>
<table>
  <thead><tr><th background-color="light-gray">字段</th><th background-color="light-gray">满分</th><th background-color="light-gray">得分</th><th background-color="light-gray">证据摘要</th></tr></thead>
  <tbody>{''.join('<tr>' + cell(f'{c} {n}') + cell(m) + cell(scores[c]) + cell(score_comment(c, int(scores[c]), m, base, relative)) + '</tr>' for c, n, m in SUBSCORES[9:12])}</tbody>
</table>
<checkbox done="false">Her/owner 确认：本周期产出是否属于不可替代融合体产出。</checkbox>
<checkbox done="false">Her/owner 确认：本周期关键产出是否已经进入组织传导、会议/OA/制度/管理动作或他人复用。</checkbox>
<checkbox done="false">Her/owner 确认：本周期是否真实释放认知时间，并投入更高价值工作。</checkbox>

<h1>D. 进化能力（10分）</h1>
<table>
  <thead><tr><th background-color="light-gray">字段</th><th background-color="light-gray">满分</th><th background-color="light-gray">得分</th><th background-color="light-gray">证据摘要</th></tr></thead>
  <tbody>{''.join('<tr>' + cell(f'{c} {n}') + cell(m) + cell(scores[c]) + cell(score_comment(c, int(scores[c]), m, base, relative)) + '</tr>' for c, n, m in SUBSCORES[12:])}</tbody>
</table>

<hr/>
<h1>基础证据</h1>
<table>
  <thead><tr><th background-color="light-gray">指标</th><th background-color="light-gray">数值</th><th background-color="light-gray">全员相对位置</th></tr></thead>
  <tbody>{metric_rows}</tbody>
</table>

<h2>Top 主题线索</h2>
<table>
  <thead><tr><th background-color="light-gray">主题占位</th><th background-color="light-gray">加权证据</th><th background-color="light-gray">群内出现</th><th background-color="light-gray">文件出现</th><th background-color="light-gray">记忆命中</th></tr></thead>
  <tbody>{topic_rows or '<tr>' + cell('无显著主题') + cell(0) + cell(0) + cell(0) + cell(0) + '</tr>'}</tbody>
</table>

<hr/>
<h1>E. 失败模式自诊断（不计分）</h1>
<table>
  <thead><tr><th background-color="light-gray">模式</th><th background-color="light-gray">本周期状况</th></tr></thead>
  <tbody>{failure_table}</tbody>
</table>

<h1>F. 下周期行动处方（不计分）</h1>
<checkbox done="false">补齐 owner alias 映射，使 owner 主动性、owner/Her 依赖关系可以程序化评估。</checkbox>
<checkbox done="false">对 C1/C2/C3 做 Her/owner 复核，区分系统证据分、Her 自检分和最终确认分。</checkbox>
<checkbox done="false">保留基础数据脚本输出作为评分输入，不在报告阶段重新翻原始聊天和 PVC 文件。</checkbox>

<hr/>
<h1>审计口径</h1>
<table>
  <thead><tr><th background-color="light-gray">项目</th><th background-color="light-gray">值</th></tr></thead>
  <tbody>
    <tr>{cell('Her ID')}{cell(her_id)}</tr>
    <tr>{cell('UID')}{cell(uid)}</tr>
    <tr>{cell('批次样本数')}{cell(score_summary.get('count'))}</tr>
    <tr>{cell('全员均分')}{cell(score_summary.get('mean'))}</tr>
    <tr>{cell('原始聊天内容')}{cell('未包含' if not privacy.get('raw_chat_content_included') else '包含')}</tr>
    <tr>{cell('密钥/token/open id')}{cell('未包含' if not privacy.get('secrets_included') else '包含')}</tr>
  </tbody>
</table>
"""


def list_existing_records(base_token: str, table_id: str) -> dict[str, dict[str, Any]]:
    records: dict[str, dict[str, Any]] = {}
    offset = 0
    while True:
        data = run_json([
            "lark-cli",
            "base",
            "+record-list",
            "--base-token",
            base_token,
            "--table-id",
            table_id,
            "--offset",
            str(offset),
            "--limit",
            "200",
            "--format",
            "json",
            "--field-id",
            "Her ID",
            "--field-id",
            "报告链接",
        ])
        payload = data["data"]
        fields = payload["fields"]
        idx = {field: index for index, field in enumerate(fields)}
        for record_id, row in zip(payload["record_id_list"], payload["data"]):
            her_id_index = idx.get("Her ID")
            if her_id_index is None or her_id_index >= len(row) or not row[her_id_index]:
                continue
            records[str(row[her_id_index])] = {
                "record_id": record_id,
                "report_link": row[idx["报告链接"]] if idx.get("报告链接") is not None and idx["报告链接"] < len(row) else None,
            }
        if not payload.get("has_more"):
            break
        offset += 200
    return records


def write_reports(args: argparse.Namespace) -> dict[str, Any]:
    scores = load_jsonl(Path(args.scores))
    evidence = by_her_id(load_jsonl(Path(args.evidence)))
    score_summary = json.loads(Path(args.score_summary).read_text()) if args.score_summary else {}
    uid_filter = selected_uids(args)
    if uid_filter is not None:
        scores = [score for score in scores if int(score["uid"]) in uid_filter]
    if args.limit:
        scores = scores[: args.limit]

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    report_dir = out_dir / "xml"
    report_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = out_dir / "report-manifest.jsonl"
    existing_manifest: dict[str, dict[str, Any]] = {}
    if manifest_path.exists() and not args.force:
        existing_manifest = by_her_id(load_jsonl(manifest_path))
    current_manifest = dict(existing_manifest)

    table_records = list_existing_records(args.base_token, args.table_id) if args.sync_links else {}
    manifest_items: list[dict[str, Any]] = []
    for index, score in enumerate(scores, start=1):
        her_id = str(score["her_id"])
        xml = render_report(score, evidence.get(her_id, {}), score_summary)
        xml_path = report_dir / f"{her_id}-fusion-report.xml"
        xml_path.write_text(xml)

        prior = existing_manifest.get(her_id)
        url = prior.get("url") if prior else None
        document_id = prior.get("document_id") if prior else None
        created = False
        if args.create_docs and (args.force or not url):
            data = run_json([
                "lark-cli",
                "docs",
                "+create",
                "--api-version",
                "v2",
                "--content",
                f"@xml/{xml_path.name}",
                "--format",
                "json",
            ], cwd=out_dir)
            doc = data["data"]["document"]
            url = doc.get("url")
            document_id = doc.get("document_id")
            created = True
            if args.sleep_seconds and index < len(scores):
                time.sleep(args.sleep_seconds)

        synced = False
        if args.sync_links and url:
            record = table_records.get(her_id)
            if not record:
                raise RuntimeError(f"missing score table row for {her_id}")
            run_json([
                "lark-cli",
                "base",
                "+record-upsert",
                "--base-token",
                args.base_token,
                "--table-id",
                args.table_id,
                "--record-id",
                record["record_id"],
                "--json",
                json.dumps({"报告链接": url}, ensure_ascii=False),
                "--format",
                "json",
            ])
            synced = True

        item = {
            "uid": score["uid"],
            "her_id": her_id,
            "xml_path": str(xml_path),
            "url": url,
            "document_id": document_id,
            "created": created,
            "synced": synced,
        }
        current_manifest[her_id] = item
        manifest_path.write_text("".join(
            json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n"
            for row in sorted(current_manifest.values(), key=lambda value: int(value.get("uid") or 0))
        ))
        manifest_items.append(item)
        print(json.dumps(item, ensure_ascii=False), flush=True)

    return {
        "reports": len(manifest_items),
        "created": sum(1 for item in manifest_items if item["created"]),
        "synced": sum(1 for item in manifest_items if item["synced"]),
        "manifest": str(manifest_path),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--evidence", required=True)
    parser.add_argument("--scores", required=True)
    parser.add_argument("--score-summary")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--uids", nargs="*", help="UIDs or ranges, for example 3 10 20-30.")
    parser.add_argument("--limit", type=int)
    parser.add_argument("--create-docs", action="store_true")
    parser.add_argument("--sync-links", action="store_true")
    parser.add_argument("--force", action="store_true", help="Recreate docs even if manifest already has URLs.")
    parser.add_argument("--base-token", default=DEFAULT_BASE_TOKEN)
    parser.add_argument("--table-id", default=DEFAULT_TABLE_ID)
    parser.add_argument("--sleep-seconds", type=float, default=0.3)
    return parser.parse_args()


def main() -> int:
    result = write_reports(parse_args())
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
